# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy FusionModoki Site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
        
      # Publish the site
      - name: Publish
        run: dotnet publish FusionModoki.csproj -p:GHPages=true -c:Release -o:publish

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.FUSION_TOKEN }}
          publish_dir: publish/wwwroot
          force_orphan: true
